services:
  db:
    image: mysql:8.0.44-debian
    container_name: local-media-gallery-mysql
    restart: always
    environment:
      MYSQL_DATABASE: local-media-gallery
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: local-media-gallery-server
    stdin_open: true
    tty: true
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      - BACKEND_SERVER_PORT=80
      - DB_HOST=local-media-gallery-mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=local-media-gallery
      - MEDIA_HOST_PATH=media
    volumes:
      - ./example_directory:/app/media

volumes:
  db_data:
